- hosts: localhost
  connection: local
  gather_facts: no           
  become: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
    homebrew_packages:
      - { name: vim }
      - { name: openssl }
      - { name: tree }
      - { name: python }
      - { name: ansible }
      - { name: git }
      - { name: wget }
      - { name: curl }
      - { name: rbenv }
      - { name: readline }
      - { name: tmux }
      - { name: node }
    homebrew_cask_packages:
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: alfred }
      - { name: skype }
      - { name: slack }
      - { name: virtualbox }
      - { name: google-japanese-ime }
      - { name: 1password }
      - { name: dropbox }
      - { name: omnifocus }
      - { name: evernote }
      - { name: iterm2 }
#      - { name: kobito }
  tasks:
    - name: tap homebrew
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: update homebrew
      homebrew: update_homebrew=yes

    # homebrew
    - name: install homebrew-packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: create homebrew-directory
      file: path=brew_info state=directory
    - name: save homebrew-packages info
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # homebrew-cask
    - name: install cask
      homebrew: name=brew-cask state=latest
    - name: install cask-packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: create cask-directory
      file: path=cask_info state=directory
    - name: save cask-packages info
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
