# homebrew-cask
- name: install cask
  homebrew: name=brew-cask state=latest
- name: install cask-packages
  homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
  with_items: homebrew_cask_packages
  register: cask_result
- name: create cask-directory
  file: path=cask_info state=directory
- name: save cask-packages info
  shell: brew cask info {{ item }} > cask_info/{{ item }}
  with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
