- name: tap homebrew
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps

- name: update homebrew
  homebrew: update_homebrew=yes

# homebrew
- name: install homebrew-packages
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: homebrew_packages
  register: brew_result
- name: create homebrew-directory
  file: path=brew_info state=directory
- name: save homebrew-packages info
  shell: brew info {{ item }} > brew_info/{{ item }}
  with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
