    - name: import secret file
      include_vars: "secret.yml"
      no_log: true

    - name: locate secret files
      copy:
        content: "{{ bashrc }}"
        dest: ~/.bashrc
        mode: 0655
      no_log: true
