- name: import secret file
  include_vars: "secret.yml"
  no_log: true

- name: locate secret key
  copy:
    content="{{ id_rsa }}"
    dest=~/.ssh/id_rsa
    mode=0600
  no_log: true

- name: locate public key
  copy:
    content="{{ id_rsa_pub }}"
    dest="~/.ssh/id_rsa.pub"
    mode=0644
  no_log: true

- name: locate circleci secret key
  copy:
    content="{{ circleci }}"
    dest=~/.ssh/circleci
    mode=0600
  no_log: true

- name: locate circleci public key
  copy:
    content="{{ circleci_pub }}"
    dest="~/.ssh/circleci.pub"
    mode=0644
  no_log: true

# [todo]locate yukofeb.pem(need to remove the last "\n")
#- name: locate aws key
#  copy:
#    content="{{ yukofeb_pem }}"
#    dest=~/.ssh/yukofeb.pem
#    mode=0400
#  no_log: true

- name: locate bash file
  copy:
    content="{{ bashrc }}"
    dest=~/.bashrc
    mode=0655
  no_log: true

- name: reload bash file
  shell: source ~/.bashrc executable=/bin/bash

- name: locate aws login file
  copy:
    content="{{ login_sh }}"
    dest="~/.ssh/login.sh"
    mode=0655
  no_log: true
