- name: import secret file
  include_vars: "secret.yml"
  no_log: true

- name: locate secret keys
  copy:
    content="{{ id_rsa }}"
    dest=~/.ssh/id_rsa
    mode=0600
  no_log: true

- name: locate public keys
  copy:
    content="{{ id_rsa_pub }}"
    dest="~/.ssh/id_rsa.pub"
    mode=0644
  no_log: true

- name: locate dot files
  copy:
    content="{{ bashrc }}"
    dest=~/.bashrc
    mode=0655
  no_log: true
