- name: import secret file
  include_vars: "secret.yml"
  no_log: true

- name: locate secret key
  copy:
    content="{{ id_rsa }}"
    dest=~/.ssh/id_rsa
    mode=0600
  no_log: true

- name: locate public key
  copy:
    content="{{ id_rsa_pub }}"
    dest="~/.ssh/id_rsa.pub"
    mode=0644
  no_log: true

- name: locate bash file
  copy:
    content="{{ bashrc }}"
    dest=~/.bashrc
    mode=0655
  no_log: true

- name: reload bash file
  shell: source ~/.bashrc executable=/bin/bash
